### ISSUE TITLE
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated

### ISSUE THREAD

**Issue by loretoparisi** [f90/Wave-U-Net#11]
It's just a deprecation warning, but it should be use to fix it

```
/Library/Python/2.7/site-packages/scipy/signal/signaltools.py:2383: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
```

**Comment by f90** [comment]
This is an issue within the scipy library, so I have pretty much nothing to do with this.
It seems other people have similar [issues](https://github.com/scipy/scipy/issues/9086), an there is a problem in general with scipy versions below 1.2, see [here](https://github.com/scipy/scipy/pull/8944)

I noticed that we are using scipy 1.1 and so probably this will be fixed by updating to 1.2, however it is not available via pip as far as I can tell, so I think we are going to have to ignore it for now.

I am going to leave the issue open so that when scipy 1.2 comes out I will remember to try to update the project to that.

Thanks for reporting.

**Comment by f90** [comment]
Scipy 1.2 was released via pip now. If you take the Wave-U-Net virtualenv and upgrade your scipy package via 
```
pip install --upgrade scipy
```
to install the new 1.2 version, can you verify that this warning disappears?

**Comment by loretoparisi** [comment]
@f90 okay we will have a look cc!

**Comment by f90** [comment]
Closing this since I didn't have this issue anymore after updating...

**Comment by heavyrick** [comment]
I had the same issue, doing this solved for me:

`pip install --upgrade scipy`
