### ISSUE TITLE
How to Install Tensorflow on Python 2.7 ?

### ISSUE THREAD

**Issue by brunobulgaron** [f90/Wave-U-Net#28]
Hi there.
I'm having this error while trying to install Tensorflow on Python 2.7

"Could not find a version that satisfies the requirement tensorflow-gpu==1.8.0 (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for tensorflow-gpu==1.8.0 (from -r requirements.txt (line 3))"

I'm not very familiar with these things, is there anything that I'm missing before installing this?

Thanks!

**Comment by f90** [comment]
Hey, which system are you on? MacOS, Windows, Linux?
Check that you are actually using a Python 2.7 environment with ```python --version```. Also make sure your pip is up-to-date:

```
pip install --upgrade pip
```

**Comment by brunobulgaron** [comment]
I'm using Windows 7 64bit, Python 2.7.13 and Pip's version is 19.0

**Comment by brunobulgaron** [comment]
I've tried running the command "python Predict.py with cfg.full_44KHz" and got this error (screenshot attached)
![Sem título](https://user-images.githubusercontent.com/50299808/57203149-d36c4d80-6f83-11e9-813e-bb27859f25f5.png)

**Comment by f90** [comment]
Yes that looks like Tensorflow is not properly installed yet. If you run python, and then execute something like
```
import tensorflow as tf
sess = tf.Session()
```
does that work or also throw an error? If that gives you an error as well, it is definitely not a problem on my end/in my Wave-U-Net code, so in that case please consult online sources to properly install Tensorflow on your system first. A quick search on Google brought up a lot of Windows people having trouble with pip installation and many suggested solutions, so that would be a good start for you.
Good luck!

**Comment by f90** [comment]
Did you make it work in the end?

**Comment by HIN0209** [comment]
"TensorFlow supports Python 3.5.x and 3.6.x on Windows." Hence you can not use tensorflow with Python 2.7 on Windows.
https://stackoverflow.com/questions/50044649/how-to-install-tensorflow-for-python-2-7#

**Comment by f90** [comment]
Thanks for the information on that, @HIN0209 
Going to close this since OP needs to switch to Linux/MacOS. Alternatively one can try Python 3, which I think my code is fully or almost fully compatible with, but I dont give any guarantees on correctness there. If someone wants to port it properly and submit a pull request however, I am happy to consider switching the codebase over to Python 3!
