### ISSUE TITLE
Index out of range errors when using ccmixter

### ISSUE THREAD

**Issue by wildermuthn** [f90/Wave-U-Net#3]
I had some trouble getting this to run with the ccmixter tracks included, using `python Training.py with full`. It appears that the ccmixter tracks are tuples of length 3, while the musdb tracks are of length 6. 

The following line doesn't take that into account, and returns index out of range errors. I added a conditional to check for the length of the tuple. Not sure if I did something wrong or not, but I'm just throwing this out there in case anyone else runs into it:

https://github.com/f90/Wave-U-Net/blob/master/Training.py#L362

**Comment by f90** [comment]
Hello,

I revamped this section of the code entirely to make it more efficient, and resolved this in the process. Please pull the latest version and try running the code again. I put the configurations into their own file, so you now need to use ``python Training.py with cfg.full``, just FYI. Also, there could be a slight problem now when trying to load models that you already trained with the older version since I removed a global variable we didn't really need. You can circumvent this manually if it is really important though.

Looking forward to hear from you whether this resolves the issues, and whether the dataset loading works flawlessly now.

**Comment by f90** [comment]
Since I didn't hear back from you I assume this is issue is resolved after my code rewrite. Going to close this issue therefore. Feel free to open it again if the problem persists, though.
