### ISSUE TITLE
How to adapt for real-time / streaming?

### ISSUE THREAD

**Issue by tensorfoo** [f90/Wave-U-Net#36]
Suppose I'm reading audio from a live music performance. Is it possible to do real time vocal extraction using wave-u-net? How small chunks of audio would you recommend using and if you could please give some pointers on how to go about making the modifications to process a chunk at a time. Many thanks for this wonderful project.

**Comment by f90** [comment]
Hey, one solution that I am pretty sure would work is to reduce the context a bit that the Wave-U-Net needs by reducing the number of layers, this way if you use it as new chunks of audio come in, you have less delay. Since the delay is just the amount of context the net needs on the right  hand side + the target output window size  (in my works ~6 sec). 

Downside is that the performance would likely degrade since you are also not allowing the network to look far into the past for prediction. But this would not require adapting the code at all basically.

The other option would be to show the network as target outputs not the source signal at the CENTRE of the input excerpt, but rather the source signal somewhat to the right of the centre, which would reduce delay during prediction, and also changing the cropping in the crop-and-concat operation to retain more of the right-most features, so you are essentially asking it to predict the source activity at the later part of the input. This also doesn't require too much code change but I am not sure how well it will predict in this setting, since now it needs to extract features more "asymmetrically". Might still work though!

**Comment by f90** [comment]
Closing this as real-time usage is a bit too complicated to add to this project.
